name: Build Windows Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.4'
        channel: 'stable'
        cache: true
        
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code (optional)
      run: flutter analyze || true
      continue-on-error: true

    - name: Run tests (optional)
      run: flutter test || true
      continue-on-error: true

    - name: Prepare Windows assets
      run: |
        # 只保留 Windows 平台的可执行文件
        Remove-Item -Path "assets/bin/N_m3u8DL-RE" -Force -ErrorAction SilentlyContinue
        Remove-Item -Path "assets/bin/ffmpeg" -Force -ErrorAction SilentlyContinue
        Write-Host "Windows assets prepared - keeping .exe files only"
      shell: powershell

    - name: Build Windows Release
      run: flutter build windows --release

    - name: Debug - List build directory structure
      run: |
        Write-Host "Listing build directory structure:"
        if (Test-Path "build") {
          Get-ChildItem -Path "build" -Recurse -Directory | Select-Object FullName
          Write-Host "Looking for executable files:"
          Get-ChildItem -Path "build" -Recurse -Filter "*.exe" | Select-Object FullName
        } else {
          Write-Host "Build directory does not exist"
        }
      shell: powershell

    - name: Create release archive
      run: |
        # Find the exe file and its directory
        $exeFile = Get-ChildItem -Path "build" -Recurse -Filter "shiplus.exe" | Select-Object -First 1
        if ($exeFile) {
          Write-Host "Found exe at: $($exeFile.FullName)"
          $releaseDir = $exeFile.Directory.FullName
          Write-Host "Release directory: $releaseDir"

          # Create archive from the directory containing the exe
          Set-Location $releaseDir
          $archivePath = Join-Path $env:GITHUB_WORKSPACE "shiplus-windows-release.zip"
          7z a -tzip $archivePath *
          Write-Host "Created archive: $archivePath"
        } else {
          Write-Host "ERROR: Could not find shiplus.exe"
          exit 1
        }
      shell: powershell
        
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: shiplus-windows-release
        path: shiplus-windows-release.zip
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: shiplus-windows-release.zip
        name: Release ${{ github.ref_name }}
        body: |
          ## Windows Release
          
          ### 安装说明
          1. 下载 `shiplus-windows-release.zip`
          2. 解压到任意文件夹
          3. 运行 `shiplus.exe`
          
          ### 系统要求
          - Windows 10 或更高版本
          - x64 架构
          
          ### 包含文件
          - `shiplus.exe` - 主程序
          - `flutter_windows.dll` - Flutter 运行时
          - `data/` - 应用资源文件
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
